{115}{166}Okay! This is it! We are gonna get married!
{167}{232}Are you sure you wanna do this?
{233}{343}Well. hello, Mrs. Ross!
{344}{461}Well, hello, Mrs. Rachel!
{462}{611}Wait! Okay!
{612}{628}Whoa!
{629}{699}Oh my God!
{700}{750}Come on Pheebs! Hurry! hurry! Hurry! Hurry!
{751}{838}Okay! Okay! Okay!
{839}{977}Oh my God!! Is everybody getting married?!
{978}{1026}N- No running in the chapel!
{1027}{1099}Hey! Don't you give me any of your...Hey!
{1100}{1149}Hey!
{1150}{1174}What are you guys doing here?
{1175}{1215}Ross and Rachel left us a message saying
{1216}{1282}they were getting married! <br/>Isn't that why you guys are here?
{1283}{1310}Yes! Well that- yes.
{1311}{1430}Why else would we be here?
{1431}{1480}Well! What happened? Did we miss it?
{1481}{1513}We actually missed it.
{1514}{1616}Well, maybe you wouldn't have had you run in the chapel!
{1617}{1647}This is insane!
{1648}{1679}What's the big deal, y'know?
{1680}{1741}It's not like it's a real marriage.
{1742}{1795}What?
{1796}{1923}Yeah, if you get married in Vegas, <br/>you're only married in Vegas.
{1924}{1960}What are you talking about?
{1961}{1996}If you get married in Vegas<br/>you're married everywhere.
{1997}{2042}Really?
{2043}{2085}Yeah!
{2086}{3630}Oh my God!? Eh! Well¡¦
{3631}{4025}Ohhh!
{4026}{4065}Why are we in bed together?
{4066}{4230}I don't know. Do- do you have any clothes on?
{4231}{4253}Yeah.
{4254}{4272}Really?
{4273}{4567}No! <br/>But we- we didn't have¡¦sex- uh, did we?
{4568}{4708}I mean, I don't remember much about last night, <br/>it was such a blur.
{4709}{4817}Oh! I remember laughing! I laughed a lot.
{4818}{4920}And we didn't have sex.
{4921}{5105}Ohh, I mean, we were really drunk. <br/>I'm just glad we didn't do anything stupid.
{5106}{5273}Tell me about it.
{5274}{5403}Mornin' Pheebs. <br/>Well, my movie has officially been canceled.
{5404}{5510}Oh Joey, I'm so sorry. <br/>You want some of my breakfast?
{5511}{5573}Nah, I'm too depressed to eat.
{5574}{5638}I'll probably eat in like 5 minutes.
{5639}{5731}So I guess I'll just fly home with you guys, <br/>what time's your flight?
{5732}{5765}What about my cab?
{5766}{5830}I don't need that anymore.
{5831}{5893}No, Joey! You borrowed my cab, <br/>you have to drive it back.
{5894}{5969}I don't want to drive all the way back by myself, <br/>I get so lonely.
{5970}{6033}Oh? ooh! How about you come with me?
{6034}{6071}I don't know, it's such a long trip.
{6072}{6273}It'll be great! We- we could talk, and play games! Huh? <br/>This could be our chance to like renew our friendship.
{6274}{6382}Are you asking me to have a frenaissance?
{6383}{6427}Sure?
{6428}{6580}All right. Although I don't think we need one, <br/>I never stopped loving you.
{6581}{6600}Hi!
{6601}{6634}Hey.
{6635}{6693}So, has anyone talked to Dr. and Mrs. Geller yet?
{6694}{6777}Um- hmm, yeah. They left me a message, <br/>they should be here any minute.
{6778}{6893}Where is the waitress? I'm starving!
{6894}{6974}It's a buffet man.
{6975}{7094}Oh, here's where I win all my money back!
{7095}{7121}Listen, I gotta talk to you.
{7122}{7387}Sure! What's up?
{7388}{7439}Monica and I almost got married last night.
{7440}{7576}Oh my God! That's huge!
{7577}{7768}Wait a minute, why come I wasn't invited? <br/>And who was going to be your best man? <br/>Don't say,"Ross." Do not say,"Ross."
{7769}{7844}Look, I just don't think Monica and I are ready to get married yet!
{7845}{7971}Y'know? I mean, I love her and everything<br/>but seeing Ross and Rachel coming out of that chapel
{7972}{8100}was like a, like a wake- up call that Monica and<br/>I are moving so fast. Y'know?
{8101}{8160}And, how do I tell her without crushing her?
{8161}{8323}Oh! Tell her she's not marriage material.
{8324}{8381}What?
{8382}{8645}Girls say it to me all the time! And believe me, <br/>if she's anything like me, she's just gonna be relieved.
{8646}{8742}How do I tell Chandler that it's too soon. <br/>It's gonna break his heart,|he's not gonna think that I don't love him anymore.
{8743}{8766}Well you don't.
{8767}{8800}Yes I do!
{8801}{8892}Good! Good! I was just testing you.
{8893}{8907}Hi.
{8908}{9005}Oh hi! Hi! Y'know, we were just talking about bacon.
{9006}{9187}No, we were talking about tennis. Tennis is more believable.
{9188}{9548}Hey!
{9549}{9568}What?
{9569}{9698}Are we gonna talk about what you guys did last night? Or¡¦
{9699}{9700}I don't know.
{9700}{9773}What do you mean last night? Nothing, nothing uh, happened last night.
{9774}{9799}Yeah!
{9800}{9923}Uh- huh! Ross invited us all to watch.
{9924}{9991}Rach! We weren't gonna miss our friends getting married!
{9992}{10093}Who got married?
{10094}{10147}You did.
{10148}{10413}What? Hello! We didn't get married. <br/>No! We didn't get married! That's ridiculous!
{10414}{10478}We- we- we? I remember being in a chapel.
{10479}{10486}Oh my God.
{10487}{10575}I- They would not let us get married<br/>when we were that drunk!
{10576}{10597}No!
{10598}{10705}They let you get married when you're drunk! <br/>Most people who get married in Vegas are drunk!
{10706}{10796}Hell, I'm drunk right now!
{10797}{10907}What? I can't have a mimosa with breakfast? I'm on vacation!
{10908}{10933}What are you guys gonna do?
{10934}{10998}Well, I guess we just find a divorce lawyer?
{10999}{11144}Well, I think, I think, Ross already has one.
{11145}{11254}Now, this one's free, right? <br/>Because you paid for the first two, so the third one's free.
{11255}{11375}Laugh it up, but the joke's on you. <br/>Because we don't need to get divorced, okay?
{11376}{11456}We we're just gonna get an annulment.
{11457}{11579}An annulment? Ross! I don't think surgery's the answer here.
{11580}{11657}Oh- oh, that's your thing.
{11658}{11700}What?
{11701}{11790}You're thing. You're thing. Y'know? <br/>You're the guy who gets divorced.
{11791}{11838}Oh yeah!
{11839}{11965}No- no, that's- that's not my thing! <br/>I do not love getting divorced!
{11966}{12064}Yes you do! This is your third divorce!
{12065}{12122}You love divorce so much you're probably gonna marry it!
{12123}{12312}Then it won't work out and you're gonna have to divorce it, <br/>divorcing guy.
{12313}{12522}I'm so drunk.
{12523}{12563}So, what do you think we should do?
{12564}{12633}I don't know. But I- I- I know I love you!
{12634}{12796}I know I love you!
{12797}{12950}So where are we on the whole going back to the place<br/>where they have all the marriages thing? I love you.
{12951}{13153}That's a good question. Look umm, last night we let the dice decide.|Maybe we should leave it up to fate again. I love you!
{13154}{13211}Yes, we don't get married unless there's a sign!
{13212}{13354}Okay, so say uh, say you roll another eight<br/>then there's a definite sign that we should get married.
{13355}{13499}All right, eight we get married, <br/>but 2, 3, 4, 5, 6, 7, 9, 10, 11, 12 we don't get married.
{13500}{13514}Sounds great.
{13515}{13560}Okay.
{13561}{13621}Coming in, we got a shooter! Money please.
{13622}{13635}Ready?
{13636}{13663}Ready!
{13664}{13776}Come on eight.
{13777}{13871}Yes, yes eight.
{13872}{13976}Eight! Easy eight.
{13977}{14028}Wow! I can't believe I actually rolled an eight.
{14029}{14169}That was so unlikely. Well, let's get married! I guess.
{14170}{14269}Wait a minute. <br/>That wasn't a hard eight! Last night I rolled a hard eight.
{14270}{14367}That's right! It was the wrong kind of eight, no wedding! Damnit!
{14368}{14486}I wanted it so bad!
{14487}{14589}Wanna go pack? <br/>Yeah.
{14590}{14627}We're doing the right thing, right?
{14628}{14669}Ohh, of course we are!
{14670}{14721}We left it up to fate.
{14722}{14989}If we were supposed to get married there<br/>would be a clear- cut sign.
{14990}{15195}Okay, you have 19 questions left. Use them wisely.
{15196}{15247}Come on Joey! You can't win if you don't ask any
{15248}{15274}QUESTIONS!!!
{15275}{15367}What?
{15368}{15407}Well, you promised me a fun road trip!
{15408}{15499}We've been on the road six hours and<br/>you've been asleep for five and a half!
{15500}{15584}We are switching at the next rest stop and<br/>you are going to drive all the way back!
{15585}{15696}That will be your punishment, you greedy sleeper!
{15697}{15736}All right. All right.
{15737}{15935}Yeah! And until then you are going to sing to me<br/>because the radio's broken and you are selfish<br/>but have a nice voice.
{15936}{15955}Really? I don't¡¦
{15956}{15985}Sing!!
{15986}{16267}¢¹I wanna rock and roll all night!
{16268}{16825}'Man, this is a long drive! Are my eyes open? No! '
{16826}{17016}Morning!
{17017}{17043}Hey!
{17044}{17129}Hey, hubby!
{17130}{17257}Yeah. Yeah, actually um, I wanted to talk to you<br/>about that whole annulment thing?
{17258}{17272}Uh- huh.
{17273}{17599}I'm not going to do that.
{17600}{17735}Okay! So, we'll just stay married.
{17736}{17769}Yes, exactly!
{17770}{17897}And I will make everyone call me Mrs. Geller!
{17898}{18057}Wow! This is so amazing. <br/>I uh, I really thought I'd have to talk you into this more.
{18058}{18189}Okay, see now I'm scared because I don't actually think you're kidding.
{18190}{18501}I'm- I'm not kidding. Look I- I, I can't have three failed marriages. <br/>I can't. Okay? I- I am not gonna be that guy!
{18502}{18639}What- wh- what so we'll just stay married forever?
{18640}{18811}Okay, look, how is this gonna affect you? Really?
{18812}{19119}I mean you fill some form out once and a while<br/>and instead of checking the box that says Ms you check the box that<br/>says Mrs.! It's right next to it!
{19120}{19189}Ohh, okay, I'm sorry. You're right. Y'know what?
{19190}{19401}We absolutely can stay married, <br/>because I was under the impression <br/>that the boxes were far away from each other.
{19402}{19603}All right, look, just please, take a moment here<br/>and think about what you're asking of me.
{19604}{19766}I'm asking you to do me a favor.
{19767}{19859}You are asking me to be your wife!
{19860}{20081}And as my wife I think you should grant me this favor.
{20082}{20129}That kid really kicked me hard on the plane.
{20130}{20165}Well you did pull his hair.
{20166}{20210}He took my snack!
{20211}{20241}I'm not getting into this again!
{20242}{20345}Okay! Oh God, y'know what? It's really bad.
{20346}{20651}Well, I told you not to walk. Here. <br/>There. Okay.
{20652}{20683}This doesn't mean anything, does it?
{20684}{20701}No!
{20702}{20815}Okay.
{20816}{20979}How could you pick up a hitchhiker? He could be a rape, <br/>a rapist or a killer or something!
{20980}{21061}Don't you think I asked him that before he got in?
{21062}{21133}Y'know what? I'm not talking to you! You go back to sleep!
{21134}{21160}And you, are you a rapist?
{21161}{21188}No!
{21189}{21243}Do you like car games?
{21244}{21295}Yeah, y'know the license plate game?
{21296}{21359}I love the license plate game!
{21360}{21398}Ooh, I'll play! I'll play!
{21399}{21614}No- No! You need your sleep. Night- night! Shh!
{21615}{21655}Hey! <br/>Hey!
{21656}{21835}Listen, I know you wanted to talk to me, <br/>but I have an idea that may make you want to stay married.
{21836}{22044}We register, and you get to keep all the presents!
{22045}{22312}No! Ross, come on! No! Listen, <br/>look I thought a lot about how to tell you this and the bottom line, <br/>Ross, is we can not stay married.
{22313}{22391}I don't know if it's true. <br/>Oh b- b- but it is!
{22392}{22601}Oh, okay, y'know what this is? <br/>This is a difference of opinion.
{22602}{22641}And when that happens in a marriage...
{22642}{22799}Oh Ross, come on! This is not, this is not a marriage!! <br/>This is the world's worst hangover!
{22800}{22949}Ross, listen, if you do not get this annulment, I will!
{22950}{23021}All right. All right, I'll do it.
{23022}{23326}Thank you. <br/>Hey- hey umm, uh, is there, is there any such thing as an annulment shower?
{23327}{23359}Wait! Wait! There is the train station!
{23360}{23437}This is where I get off. Well, I have your address and phone number.
{23438}{23615}And I have your name and the fact that<br/>you're a drifter, so the ball's pretty much in your court.
{23616}{23860}All right, see ya Pheebs.
{23861}{24095}Come on Pheebs! I can't take this anymore! <br/>Please Talk to me! Let- let me make it up to you. Huh?
{24096}{24228}¢¹Ground control to Major Tom.
{24229}{24376}¢¹Commencing countdown, engines on.
{24377}{24553}¢¹Take your protein pills and put your helmet on!
{24554}{24771}Stop it! Stop it no! That's not fair! <br/>Y'know I can't resist that beautiful voice!
{24772}{24840}Pheebs, I am so sorry!
{24841}{24961}I know I promised you a fun road trip with your friend and<br/>I didn't deliver.
{24962}{25103}But- but- but now I know that<br/>you think being awake is an important part of friendship!
{25104}{25276}So, so, so I will strive to- to stay awake for as long as I know you.
{25277}{25369}You can still sleep at night and stuff.
{25370}{25582}Well, thank you. So, can we play 20 Questions now? <br/>I've got a really good one! <br/>I've been thinking about it since Kansas.
{25583}{25746}Okay. Is it a kind of hot sandwich?
{25747}{25807}Yes.
{25808}{25849}Is it a meatball sub?
{25850}{26127}That is incredible! You are the master!
{26128}{26178}Huh, that's funny. You look like you're gonna be the¡¦
{26179}{26275}No, don't say it! Don't even think it!
{26276}{26454}All right. Okay Chandler, enjoy your handful.
{26455}{26527}All right, should we just, should we just get married? <br/>Y'know? I mean should we just do it?
{26528}{26595}All the signs are telling us to do it.
{26596}{26651}I'm sick of the signs! It's too fast, I'm happy the way things are!
{26652}{26680}Me too!
{26681}{26707}I don't want things to change! Do you?
{26708}{26724}No!
{26725}{26803}All right then, then nothing changes! Everything is great! <br/>Everything stays the same! And you go unpack
{26804}{26929}because it's been three days and it's driving me insane!
{26930}{27230}Jeez, relax! It's not like we're mar- ah- ah!!
{27231}{27348}Y'know I was thinking, what if I uh, unpack here?
{27349}{27446}Then all your stuff would be here.
{27447}{27592}Well, what if all my stuff was here?
{27593}{27724}Then you'd be going back and forth all the time, <br/>I mean it doesn't make any sense.
{27725}{27974}Okay. What if we lived together and you understand what I'm saying?
{27975}{28037}Live together?
{28038}{28091}There have been no signs for that.
{28092}{28260}Me asking is kind of a sign.
{28261}{28363}YES!!!!!!!! <br/>Okay!!!!!
{28364}{28492}Yes! Okay! Okay! Wait- wait- wait!
{28493}{28508}Okay.
{28509}{28542}Here's your key <br/>Oh thanks.
{28543}{28640}Here's your key. All right, you have to christen it! <br/>Now, go out and come back in!
{28641}{28736}The door hasn't been locked in five years, but okay! <br/>Ready?
{28737}{28776}Ready!
{28777}{28879}Okay, a little problem. The key broke in the lock and I can't get in!
{28880}{28946}Wait! Oh my God! I can't get out!
{28947}{28972}This is not a sign!
{28973}{29013}No, it's not a sign! It's a very old key!
{29014}{29038}It's an old key!
{29039}{29096}Oh my God it's old!
{29097}{29222}I love you! <br/>I love you!
{29223}{29430}Are you hugging the door right now.
{29431}{29489}No.
{29490}{29607}Yeah- yeah, me neither.
{29608}{29632}Hey!
{29633}{29707}Hey, so did everything go all right with the annulment?
{29708}{29781}Oh, yeah, no problems. It's all taken care of.
{29782}{29894}Ross, thank you. Hey, do you guys wanna go see a movie?
{29895}{29924}Oh yeah, why not?
{29925}{29945}Pheebs?
{29946}{30025}No thanks, I've already seen one.
{30026}{30189}Okay, umm, I'm gonna get my sweater.
{30190}{30227}Okay. <br/>You uh, you wanna hear something weird?
{30228}{30301}Always.
{30302}{30399}I didn't get the annulment.
{30400}{30424}What?
{30425}{30859}We're still married! Don't tell Rachel. See you later.
{30860}{30890}What are you doing?
{30891}{30922}The key's stuck in the lock.
{30923}{31199}I can fix it. Hold on. <br/>Watch out. Watch out.
{31200}{31229}It still doesn't work.
{31230}{31251}I'm not finished.
{31252}{31532}Oh.
{31533}{31633}Nice job Joe! You're quite the craftsmen.